services:
  homeassistant:
    container_name: ha1
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/armadsen/docker/ha1/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: false
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
