timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'

auth:
  enabled: true # Don't change this

tls:
  enabled: false

mqtt:
  enabled: true
  host: 192.168.1.67
  port: 1883

# Google Corel edgeTPU. On M720Q connect to rear panel, a blue USB.  2x USB 3.1 Gen 2.
detectors:
  coral:
    type: edgetpu
    device: usb
# Corel end

# Detector for yolov9 model
#detectors:
#  onnx:
#    type: onnx

#model:
#  model_type: yolo-generic
#  width: 320
#  height: 320
#  input_tensor: nchw
#  input_dtype: float
#  path: /config/model_cache/yolov9-t-320.onnx
#  labelmap_path: /labelmap/coco-80.txt
# Yolo end

# Object detector is Intel GPU.
#detectors:
#  ov:
#    type: openvino
#    device: GPU

# Objector detector model (for Intel GPU)
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  path: /openvino-model/ssdlite_mobilenet_v2.xml
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
# Intel GPU end

# Setup reviews in review tab in frigate. [] means empty list
review:
  alerts:
    labels:
      - dog
      - cat

go2rtc:
  streams:
    Driveway: # Watching/Recording
      - rtsp://192.168.1.50:554/live1.sdp
    Driveway_sub: # Detection
      - rtsp://192.168.1.50:554/live2.sdp
    Bryggers: # Watching/Recording
      - rtsp://192.168.1.51:554/live1.sdp
    Bryggers_sub: # Detection
      - rtsp://192.168.1.51:554/live2.sdp
    Loft: # Watching/Recording
      - rtsp://192.168.1.52:554/live1.sdp
    Loft_sub: # Detection
      - rtsp://192.168.1.52:554/live2.sdp
    BryggersD340P:
      - ffmpeg:http://192.168.1.79/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=abcd1234
    BryggersD340P_sub:
      - ffmpeg:http://192.168.1.79/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=abcd1234
    EntreD340P:
      - ffmpeg:http://192.168.1.57/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=abcd1234
    EntreD340P_sub:
      - ffmpeg:http://192.168.1.57/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=abcd1234

# Global hwaccel configuration to avoid repetition at each camera
ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 5
    mode: motion

cameras:
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 40000       # Minimum size in pixels (e.g. 100x50)
          min_score: 0.5       # Default is 0.5
          threshold: 0.7       # Default is 0.7
        dog:
          min_area: 2500       # Earlier this was 2000
          max_area: 20000
          threshold: 0.6       # Default is 0.7
        cat:
          min_area: 2500       # Earlier this was 2000
          max_area: 20000
          threshold: 0.6       # Default is 0.7
    motion:
      threshold: 30            # default is 30
      contour_area: 10         # default is 10
      improve_contrast: true
      mask:
        - 0.006,0.398,0.071,0.376,0.082,0.499,0.078,0.556,0.106,0.651,0.079,0.684
        - 0.314,0.231,0.093,0.2,0.085,0.115,0.301,0.015
        - 0.086,0.002,0.086,0.031,0.164,0.033,0.167,0.003
  Bryggers:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Bryggers_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Bryggers
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          min_area: 20000      # Minimum size in pixels (e.g. 100x50)
          threshold: 0.7       # Default is 0.7
        dog:
          min_area: 2000       # Earlier this was 2000
          max_area: 75000
          threshold: 0.5       # Default is 0.7
        cat:
          min_area: 2000       # Earlier this was 2000
          max_area: 50000
          threshold: 0.5       # Default is 0.7
        car:
          min_area: 25000
    motion:
      threshold: 30            # default is 30
      contour_area: 10         # default is 10
      improve_contrast: true
      mask:
        - 0.087,0.003,0.161,0.003,0.162,0.029,0.087,0.034
        - -0.001,0.187,0.154,0.311,0.289,0.082,0.197,0.02
        - 0.278,0.998,0.323,0.93,0.369,0.928,0.382,0.954,0.4,0.998
        - 0.785,0.993,0.818,0.899,0.849,0.833,0.886,0.789,0.919,0.794,0.948,0.823,0.963,0.854,0.971,0.881,0.984,0.923,0.952,0.997
        - 0.489,0.025,0.521,0.029,0.546,0.044,0.566,0.059,0.595,0.08,0.617,0.103,0.638,0.128,0.656,0.147,0.679,0.169,0.695,0.188,0.715,0.211,0.746,0.236,0.759,0.252,0.751,0.326,0.733,0.432,0.719,0.507,0.707,0.576,0.65,0.599,0.625,0.527,0.599,0.444,0.575,0.376,0.551,0.342,0.532,0.331,0.491,0.331,0.452,0.331,0.421,0.337,0.393,0.334,0.384,0.291,0.385,0.252,0.381,0.206,0.379,0.165,0.389,0.126,0.401,0.082,0.412,0.059,0.419,0.029,0.428,0.013,0.441,0.01,0.459,0.01
        - 0.998,0.412,0.967,0.375,0.928,0.34,0.894,0.293,0.846,0.252,0.802,0.211,0.765,0.178,0.727,0.152,0.697,0.115,0.654,0.083,0.65,0.002,0.868,0.005,0.995,0.005
        - 0.431,-0.002,0.652,0.003,0.649,0.1,0.645,0.142
        - 0.407,0.123,0.298,0.146,0.196,0.033,0.198,0.005,0.455,0.005
    zones: {}
  Loft:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Loft_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Loft
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 50000       # Minimum size in pixels (e.g. 100x50)
    motion:
      enabled: true
      threshold: 10        # Sensitivity to pixel changes (lower = more sensitive). Default: 30
      contour_area: 5     # Minimum area of motion to trigger detection. Default: 10
      improve_contrast: true
      mask:
        - 0.088,0.005,0.087,0.038,0.168,0.039,0.17,0.003
        - 0.769,0.813,0.779,0.975,0.827,0.956,0.82,0.82
  BryggersD340P:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BryggersD340P_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/BryggersD340P
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      fps: 10 # default is 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          min_area: 3000       # Minimum size in pixels (e.g. 100x50)
    motion:
      mask:
        - 0.16,0.838,0.233,0.858,0.258,0.881,0.286,0.931,0.306,0.994,0.154,0.995
        - 0.358,0.679,0.352,0.623,0.35,0.56,0.365,0.52,0.4,0.495,0.43,0.494,0.449,0.514,0.457,0.487,0.489,0.462,0.499,0.484,0.505,0.533,0.51,0.574,0.504,0.629,0.502,0.671,0.444,0.684,0.387,0.69
        - 0.852,0.994,0.873,0.903,0.886,0.821,0.904,0.737,0.935,0.692,0.976,0.673,0.998,0.668,0.996,0.975
        - 0.501,0.498,0.639,0.513,0.706,0.525,0.713,0.579,0.714,0.642,0.707,0.736,0.694,0.794,0.641,0.818,0.608,0.785,0.568,0.736,0.518,0.689,0.488,0.66
        - 0.198,0.013,0.201,0.05,0.357,0.05,0.361,0.008
    record:
      enabled: true
      retain:
        days: 5
        mode: all # to enable that HA can start a recording using a shell call.
  EntreD340P:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/EntreD340P_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/EntreD340P
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      fps: 10 # default is 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 100000       # Minimum size in pixels (e.g. 100x50)
        dog:
          min_area: 2000
          max_area: 30000
        cat:
          min_area: 2000
          max_area: 30000
    motion:
      mask: 0.198,0.005,0.2,0.058,0.351,0.057,0.356,0.011
    record:
      enabled: true
      retain:
        days: 5
        mode: all # to enable that HA can start a recording using a shell call.
camera_groups: {}
detect:
  enabled: true
version: 0.16-0
