services:
  webtop:
#    image: lscr.io/linuxserver/webtop:ubuntu-kde
    image: webtop-vscode
    container_name: webtop
    privileged: false
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /home/armadsen:/config/Desktop
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
