services:
  frigate:
    container_name: frigate
    privileged: true # needed to enable frigate to access GPU
    environment:
      - TZ=Europe/Copenhagen
      - LIBVA_DRIVER_NAME=i965 # Needed for VAAPI HW acceleration. i965 is needed for i7 and I have Intel Core i7-8700T, 32GB RAM, 512GB SSD,
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: '1000mb'
    volumes:
      - ./config:/config
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "5000:5000" # unsecure, used by HA
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, seems correct for my hardware. Used for video decoding.
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions. On M720Q connect to rear panel, a blue USB. 2x USB 3.1 Gen 2
